### ISSUE TITLE
pytest errors

### ISSUE THREAD

**Issue by rrenka** [underworldcode/stripy#38] opened 2019-06-04 18:16 UTC
I'm still getting errors in the tests.  Following are some excerpts from
running on my MacBook Air.

test_1a_spherical_mesh_examples.py:57:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stripy/cartesian_meshes.py:48: in __init__
 ...
>       return _nx.concatenate(arrays, 1)
E       ValueError: all the input array dimensions except for the concatenation axis must match exactly

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/shape_base.py:640: ValueError

test_1b_cartesian_mesh_examples.py:17:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stripy/cartesian_meshes.py:48: in __init__
 ...
>       return _nx.concatenate(arrays, 1)
E       ValueError: all the input array dimensions except for the concatenation axis must match exactly

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/shape_base.py:640: ValueError

>       Zi, ierr = mesh.interpolate_nearest(0.9, 0.9, Z)
E       TypeError: cannot unpack non-iterable numpy.float64 object

test_Triangulation.py:44: TypeError
 ...
        for i in range(0, size):
>           ist = np.abs(self._x - xi[i]).argmin() + 1
E           IndexError: too many indices for array

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stripy/cartesian.py:500: IndexError
 ...

>       Zi, ierr = mesh.interpolate_nearest(0.9, 0.9, Z)

test_sTriangulation.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stripy/spherical.py:557: in interpolate_nearest
 ...
>       shape = lons.shape
E       AttributeError: 'float' object has no attribute 'shape'

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/stripy/spherical.py:530: AttributeError

**Comment by brmather** [comment] 2019-06-05 00:00
I am unable to reproduce these errors on my system - @rrenka are you compiling against the latest version of the master branch? There might be some changes from the last two weeks or so that need to be pulled.

**Comment by lmoresi** [comment] 2019-06-05 00:03
Also that the tests are best run with `python setup.py test` which should then verify all the dependencies are in place.
If that verification is fragile, we can figure out why.

Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 5 Jun 2019, 10:00 AM +1000, Ben Mather <notifications@github.com>, wrote:

I am unable to reproduce these errors on my system - @rrenka<https://github.com/rrenka> are you compiling against the latest version of the master branch? There might be some changes from the last two weeks or so that need to be pulled.

**Comment by rrenka** [comment] 2019-06-05 15:22
I reinstalled the code on May 29 so I think it's current.

I executed the command 'python3 setup.py test' on both a Linux box and a Mac.
I got no errors under Linux but I got the following results under MacOS:

____________________________________ test_cubic_interpolation _____________________________________

    def test_cubic_interpolation():
    
        # we need more points for cubic interpolation
        coords = np.array([[0.0, 0.0], \
                           [0.0, 1.0], \
                           [1.0, 0.0], \
                           [1.0, 1.0], \
                           [0.1, 0.1], \
                           [0.1, 0.9], \
                           [0.9, 0.1], \
                           [0.9, 0.9]])
    
        lons, lats = coords[:,0], coords[:,1]
        mesh = stripy.sTriangulation(lons, lats)
    
        Z = mesh.lons + mesh.lats
    
        Zi, ierr = mesh.interpolate_cubic(0.5, 0.5, Z)
    
        if np.isclose(Zi, 0.94596):
            print("PASS! (Interpolation - cubic")
        else:
>           assert False, "FAIL! (Interpolation - cubic)"
E           AssertionError: FAIL! (Interpolation - cubic)
E           assert False

tests/test_sTriangulation.py:93: AssertionError

**Comment by rrenka** [comment] 2019-06-05 15:23
I hit the wrong key.  Didn't mean to close.

**Comment by lmoresi** [comment] 2019-06-05 23:27
@brmather - I'm not a fan of these isclose() tests as I am more interested to know if stuff blows up catastrophically v. potential rounding errors.  Perhaps we can have a separate set of accuracy tests that we can run if the debugging tests pass. It might also be useful to separate out the tests for optional packages associated with demonstrations in the documentation.

**Comment by brmather** [comment] 2019-06-06 05:54
OK - I've just committed some better tests for functionality that _should_ be agnostic to rounding errors eea3be0b40cfd8fb4acf90dfbc6a5e5d488a1002. @rrenka can you pull the latest changes and let us know if you still encounter errors?

**Comment by rrenka** [comment] 2019-06-06 16:26
The error in test_sTriangulation went away but I got the following error in test_Triangulation:

PASS! (Derivatives)
Traceback (most recent call last):
  File "test_Triangulation.py", line 162, in <module>
    test_nearest_nd_interpolation()
  File "test_Triangulation.py", line 20, in test_nearest_nd_interpolation
    Zi, ierr = mesh.interpolate_nearest(ix, iy, Z)
TypeError: cannot unpack non-iterable numpy.float64 object

I replaced 'Zi, ierr' by 'Zi', and the problem disappeared (all tests passed).  I am not
a Python programmer and have no idea why the error occurred when the same line
of code in test_sTriangulation was not a problem.

**Comment by brmather** [comment] 2019-06-07 05:42
Some time ago I found that a few interpolation functions broke when a scalar was passed in to `xi` or `yi` instead of a list. This has been subsequently fixed, but you might need to update `stripy` for it to be compatible with the latest series of tests.

Run this from the top-level directory after you `git pull` the latest changes from the repo:

```sh
python3 -m pip install --upgrade .
```

I think all the bugs have been squashed now, but please let me know if you encounter any more problems with the tests.

**Comment by rrenka** [comment] 2019-06-07 13:44
OK.  Success!  I can now check all the boxes on the review form.  Good work!

**Comment by brmather** [comment] 2019-06-08 09:11
Great! I'm closing this issue...

**Closed by brmather** 2019-06-08 09:11 UTC
